### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/next-preact#1]
# Motivation
We want to create a nextjs preact plugin on NPM

# Tasks
- [ ] Import Dependencies
- [ ] Refer to First Preact App for the template
- [ ] Maintain structure of app
- [ ] Publish to NPM
- [ ] Ensure that the plugin works
